/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by PayloadCMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface User {
  id: string;
  localizedField: string;
  roles: ('admin' | 'editor' | 'moderator' | 'user' | 'viewer')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}

export interface Post {
  id: string;
  title: string;
  content: string;
  author: {
    relationTo: 'users';
    value: string | User;
  };
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Category {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  parent?: {
    relationTo: 'categories';
    value: string | Category;
  } | null;
  createdAt: string;
  updatedAt: string;
}

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    posts: Post;
    categories: Category;
  };
  locale: 'en' | 'pl';
  user: User & {
    collection: 'users';
  };
}

export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
} 